//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app
    {
        public int id_app { get; set; }
        public string nom { get; set; }
        public string taille { get; set; }
        public byte[] image { get; set; }
        public string Liste_OS { get; set; }
        public string editeur { get; set; }
        public string categorie { get; set; }
        public Nullable<double> prix { get; set; }
    }
}
